### ISSUE TITLE
[Firmware] Dumping the original firmware

### ISSUE THREAD

**Issue by dreamwhite** [benbaker76/patchram#1]
Hi there,
thank you so much for releasing this tool.
Since I'm willing to do some tests with my DW1830, but at the same time I want to have a recovery plan, is there anything I can do to backup the original firmware in case anything goes wrong?
Thank you so much and have a nice day

**Comment by benbaker76** [comment]
Broadcom devices will clear their flash to default if you remove power to them for a little while so they're pretty much impossible to brick.

**Comment by dreamwhite** [comment]
> if you remove power to them for a little while

So let's suppose that I flash a firmware X on the card and for whatever reason this firmware is corrupted, if I turn off the computer the card will clear its flash, uh?

In such case, it's fantastic!

**Comment by benbaker76** [comment]
patchram also performs checks on the firmware including a check against the vendor id and product id of the device as well as a checksum of the firmware file.

The device also has checks in place during the update process to make sure it's valid.

And if the firmware itself fails in some way you can always cold boot with enough time for the flash to clear.

So yes the process is generally quite safe.

PS a good place to source a firmware for testing is [here](https://github.com/acidanthera/BrcmPatchRAM/tree/master/firmwares).

**Comment by benbaker76** [comment]
Also note that macOS will open your Bluetooth hardware in exclusive mode so you'll need to turn it off in Settings to allow patchram to access it.

**Comment by buyddy** [comment]
Does this resolve the airdrop issue from hackintosh to iOS devices?

**Comment by benbaker76** [comment]
> Does this resolve the airdrop issue from hackintosh to iOS devices?

patchram performs a DFU upgrade of the firmware to a Broadcom PatchRAM device. Essentially it does the same thing as BrcmPatchRAM but in user space. This allows you to test firmware (from Windows drivers) to see how they perform in macOS without the need to reboot using BrcmPatchRAM.

So essentially it's a testing tool for trying different firmware. I can't say whether or not it can fix Airdrop issues but it's likely some firmware will work better than others in macOS.
